import styled from "styled-components";
import Head from "next/head";
import MainHero from "../components/heros/MainHero";
import VideoImagePlaceholder from "../components/video/VideoImagePlaceholder";
import ImageGrid from "../components/imageGrid/ImageGrid";
import AudioImage from "../components/audio/AudioImage";
import SubHero from "../components/heros/SubHero";
import ImageCardCenteredCopy from "../components/ImageCards/ImageCardCenteredCopy";
import MovingImages from "../components/gifSection/MovingImages";
import SubscribeHero from "../components/heros/SubscribeHero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <MainHero />
        <FullBleed>
          <VideoImagePlaceholder />
        </FullBleed>
        <ImageGrid />
        <FullBleed>
          <AudioImage
            backgroundImage="https://mwcm.nyt.com/dam/LP/brand/1619/img/BK-audio.png"
            copy="If we can't acknowledge the truth about the institution of slavery, then how do we go on to fix the legacy of it?"
          />
        </FullBleed>
        <SubHero />
        <MovingImages />
        <SubscribeHero />
      </Wrapper>
    </div>
  );
}

// Creates a 3 column grid allow for full bleed sections.
const Wrapper = styled.div`
  display: grid;
  grid-template-columns: 1fr min(150ch, 100%) 1fr;

  & > * {
    grid-column: 2;
  }

  @media (min-width: 1040px) {
    margin-block-start: 4vh;
  }
`;

const FullBleed = styled.div`
  grid-column: 1 / -1;
`;
