import styled from "styled-components";
import Head from "next/head";
import MainHero from "../components/MainHero";
import VideoImagePlaceholder from "../components/video/VideoImagePlaceholder";
import ImageGrid from "../components/imageGrid/ImageGrid";
import ImageCard from "../components/ImageCards/ImageCardCenteredCopy";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <MainHero />
        <FullBleed>
          <VideoImagePlaceholder />
        </FullBleed>
        <ImageGrid />
      </Wrapper>
    </div>
  );
}

// Creates a 3 column grid allow for full bleed sections.
const Wrapper = styled.div`
  display: grid;
  grid-template-columns: 1fr min(150ch, 100%) 1fr;

  & > * {
    grid-column: 2;
  }

  @media (min-width: 1040px) {
    margin-block-start: 4vh;
  }
`;

const FullBleed = styled.div`
  grid-column: 1 / -1;
`;
